### ISSUE TITLE
- (void)leftInContainer:(CGFloat)left shouldResize:(BOOL)shouldResize is wrong

### ISSUE THREAD

**Issue by fieldtqy** [casatwy/HandyAutoLayout#2]
should be this:
- (void)leftInContainer:(CGFloat)left shouldResize:(BOOL)shouldResize
  {
  if (shouldResize) {
      self.width = self.x - left + self.width;
  }
  self.x = left;
  }

**Comment by casatwy** [comment]
left in container means the left offset in superview, so self.width = self.x - left + self.superview.width; is not wrong.

did this works wrong in your code?
