### ISSUE TITLE
为毛不起作用啊

### ISSUE THREAD

**Issue by wy19901227** [casatwy/HandyAutoLayout#4]
[self addConstraints:[all constraintsLeft:15.0 FromView:self]];
   [self addConstraint:[all constraintWidth:62]];
   [self addConstraint:[all constraintHeight:30]];
    [self addConstraint:[all constraintCenterYEqualToView:self]];
   [self addConstraint:[good constraintWidthEqualToView:all]];
   [self addConstraint:[good constraintHeightEqualToView:all]];
   [self addConstraint:[good constraintCenterYEqualToView:self]];
   [self addConstraints:[good constraintsLeft:15+margin FromView:self]];
    [self addConstraint:[normol constraintHeightEqualToView:all]];
   [self addConstraint:[normol constraintWidthEqualToView:all]];
   [self addConstraint: [normol constraintCenterYEqualToView:self]];
   [self addConstraints: [normol constraintsLeft:15+2_margin FromView:self]];
   [self addConstraint: [bad constraintWidthEqualToView:all]];
  [self addConstraint: [bad constraintHeightEqualToView:all]];
   [self addConstraint: [bad constraintCenterYEqualToView:self]];
   [self addConstraints: [bad constraintsRight:15.0 FromView:self]];
   [self addConstraints: [bad constraintsLeft:15+3_margin FromView:self]];

**Comment by casatwy** [comment]
你要看你是在哪儿add的constraint啊，而且addConstraint之前，有没有addsubview？
