### ISSUE TITLE
应该搞个Demo的

### ISSUE THREAD

**Issue by andi911** [casatwy/HandyAutoLayout#9]
有些还是很好懂，但是有些必须自己去写一遍才能确定

**Comment by objbee** [comment]
1.写了个小 Demo，需要的可以瞅瞅，https://github.com/idevzhou/HandyAutoLayoutDemo
2.非常好用，增加了代码可读性。感觉应用场景是这样的：设置 frame 用 UIView+LayoutMethods，可读性非常高；简单的自动布局可以用 UIView+HandyAutoLayout，比原生省了不少代码；自动布局用的比较多，还是得 Masonry

**Comment by andi911** [comment]
你这个太麻烦了啊，不过在iOS7 中还是管用的

**Comment by andi911** [comment]
可以的，用你demo的第一个方法还是好用的
